theme: minima
title: My Github page
author: vicgals
email: vicgalang.m@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, welcome to my learning at github. I'm now at the github pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
